drop table user_coins if exists;
CREATE TABLE user_coins (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1)  NOT NULL  PRIMARY KEY,
  user_id bigint NOT NULL ,
  coins integer
);

drop table transfer_log if exists;
CREATE TABLE transfer_log (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL PRIMARY KEY,
  from_user bigint  NOT NULL ,
  to_user bigint  NOT NULL ,
  coins integer NOT NULL
);

INSERT INTO user_coins(id, user_id, coins) VALUES (1, 1, 10);